Repository vimeda/shared-actions, pull requests merged in 2022-06, with the labels that each got.

#27 allow to pass build args
  .github/workflows/build-image.yaml
Labels: type: maintenance

#28 feat: add tech docs workflow
  .github/workflows/techdocs.yaml
Labels: type: feature

#29 refactor: update tech docs inputs
  .github/workflows/techdocs.yaml
Labels: type: maintenance

#30 fix: typo on parameter
  .github/workflows/techdocs.yaml
Labels: type: bug
