Repository vimeda/shared-actions, pull requests merged in 2022-07, with the labels that each got.

#31 fix: remove hard coded region
  .github/workflows/build-image.yaml
Labels: type: bug

#32 Bump lykon charts to version 0.10.10
  .github/workflows/main-deploy.yaml
  .github/workflows/release-deploy.yaml
Labels: type: dependencies

#33 Bump lykon charts to version 0.10.11
  .github/workflows/main-deploy.yaml
Labels: type: dependencies

#34 Bump lykon charts to version 0.10.11
  .github/workflows/release-deploy.yaml
Labels: type: dependencies

#35 refactor: update dependencies
  .github/workflows/build-image.yaml
  .github/workflows/dependencies.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-php.yaml
Labels: type: maintenance
